In [2]:
import torch
import torch.nn as nn

In [14]:
linear = nn.Linear(3, 4, bias=False)

# weight is of the shape (4, 3)
weight = linear.weight
print(linear.weight)

Parameter containing:
tensor([[ 0.4213,  0.1826, -0.0869],
        [ 0.1395, -0.1847, -0.5300],
        [-0.2804,  0.3575,  0.4314],
        [-0.3480, -0.2068,  0.0694]], requires_grad=True)


In [15]:
weight = weight.transpose(0, 1)
print(weight)

tensor([[ 0.4213,  0.1395, -0.2804, -0.3480],
        [ 0.1826, -0.1847,  0.3575, -0.2068],
        [-0.0869, -0.5300,  0.4314,  0.0694]], grad_fn=<TransposeBackward0>)


In [16]:
input_tensor = torch.tensor([[1.0, 2.0, 3.0]])
output_tensor = linear(input_tensor)
print(output_tensor)

tensor([[ 0.5258, -1.8197,  1.7287, -0.5534]], grad_fn=<MmBackward0>)


In [17]:
# manually compute the output
expected_output = input_tensor @ weight
print(expected_output)

tensor([[ 0.5258, -1.8197,  1.7287, -0.5534]], grad_fn=<MmBackward0>)
